### ISSUE TITLE
function naming does not conform to format standards

### ISSUE THREAD

**Issue by murphsp1** [BTrDB/btrdb-python#5]
This issue should be debated.

The method is refreshMeta() whereas the GoLang version is RefreshMeta(). In Python, this should be refresh_meta(). It would be "more pythonic" to follow the formatting standards. Should the python library conform to python formatting standards or try to match the Go Lang version?

There are some other issues with spacing that are probably just being a bit nitpicky.

**Comment by murphsp1** [comment]
As an additional element to this point, the names of the functions are written from the perspective of the developer, not necessarily the end user. Thus, more clarity could be introduced.

alignedWindows() could become query_aligned_windows() or something even more obvious to the end user.

**Comment by looselycoupled** [comment]
Method renaming was included in the v5 bindings and can currently be found in the develop branch.  Closing issue for now but can be re-opened for specific renaming requests.
